version: '3.8'

services:
  app:
    build: .
    container_name: python_app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://kts_user:kts_pass@postgres:5432/kts
    networks:
      - db_network
    volumes:
      - ./app/:/project/app
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: kts
      POSTGRES_USER: kts_user
      POSTGRES_PASSWORD: kts_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db_network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  db_network:
    driver: bridge