"""Initial tables

Revision ID: 2383847371cf
Revises: fab18709d96f
Create Date: 2025-10-06 19:26:31.062752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2383847371cf'
down_revision: Union[str, None] = 'fab18709d96f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('users', sa.Column('id_tg', sa.BigInteger(), nullable=True))
    op.drop_constraint('users_username_id_tg_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['id_tg'])
    op.drop_column('users', 'username_id_tg')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username_id_tg', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_id_tg_key', 'users', ['username_id_tg'])
    op.drop_column('users', 'id_tg')
    op.alter_column('players', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
