"""Initial tables

Revision ID: 4df9c31ecc86
Revises: 589303ecd9e6
Create Date: 2025-10-08 17:49:53.685829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df9c31ecc86'
down_revision: Union[str, None] = '589303ecd9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'description')
    # ### end Alembic commands ###
