"""Initial tables

Revision ID: d34b3832d14e
Revises: 0a8cdfa4501a
Create Date: 2025-10-04 15:59:35.167473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34b3832d14e'
down_revision: Union[str, None] = '0a8cdfa4501a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('session_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'players', ['id'])
    op.create_foreign_key(None, 'players', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.add_column('rounds', sa.Column('session_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'rounds', ['id'])
    op.create_foreign_key(None, 'rounds', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'sessions', ['id'])
    op.add_column('states', sa.Column('session_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'states', ['session_id'])
    op.create_unique_constraint(None, 'states', ['id'])
    op.create_foreign_key(None, 'states', 'sessions', ['session_id'], ['id'])
    op.create_unique_constraint(None, 'themes', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'themes', type_='unique')
    op.drop_constraint(None, 'states', type_='foreignkey')
    op.drop_constraint(None, 'states', type_='unique')
    op.drop_constraint(None, 'states', type_='unique')
    op.drop_column('states', 'session_id')
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_constraint(None, 'rounds', type_='foreignkey')
    op.drop_constraint(None, 'rounds', type_='unique')
    op.drop_column('rounds', 'session_id')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'session_id')
    # ### end Alembic commands ###
