"""Initial tables

Revision ID: e64971d082e8
Revises: 2383847371cf
Create Date: 2025-10-06 19:40:15.111675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64971d082e8'
down_revision: Union[str, None] = '2383847371cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'total_true_answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('total_true_answers', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
